# Build settings

software_type:
  - Phylogenetics Inference
  - Next Generation Sequencing
  - Phylogenetics Modelling
  - Miscellaneous

people_type:
  - Head
  - Postdoc
  - PhD student
  - Student

markdown: kramdown
kramdown:
  enable_coderay: true
  syntax_highlighter: coderay
  syntax_highlighter_opts: { line_numbers: false }

